#include "SERVO.h"

void SERVO_GPIO_Init(void) {
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	
	GPIOA->MODER &= ~GPIO_MODER_MODE0;
	GPIOA->MODER |= GPIO_MODER_MODE0_1;
	
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFSEL0;
	GPIOA->AFR[0] |= GPIO_AFRL_AFSEL0_1;
	
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPD0;
}

void TIM5_CH1_Init(void) {
	RCC->APB1ENR1 |= RCC_APB1ENR1_TIM5EN;
	
	TIM5->CR1 &= ~TIM_CR1_DIR;
	
	// 4MHz MSI clock
	// To get 100kHz = 4Mhz/(PSC+1)
	// PSC = 40-1 = 39
	TIM5->PSC = 39;
	
	TIM5->ARR = 2000;
	
	TIM5->CCMR1 &= ~TIM_CCMR1_OC1M;
	TIM5->CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2;
	
	TIM5->CCER |= TIM_CCER_CC1E;
	
	TIM5->CCR1 = 1000;
	
	TIM5->CR1 |= TIM_CR1_CEN;
}



void SERVO_L90(void) {
	TIM5->CCR1 = 55;
}

void SERVO_R90(void) {
	TIM5->CCR1 = 255;
}